### ISSUE TITLE
Possible error in an example script.

### ISSUE THREAD

**Issue by Nikismyname** [cemuka/UnityRuntimeNodeEditor#15]
In this line:
https://github.com/cemuka/UnityRuntimeNodeEditor/blob/2e3deb6c9b78673e01ab3935a50a617f7988a4d6/Assets/Example/Scripts/MathOperationNode.cs#L58

I think there should be a remove instead of add.

**Comment by cemuka** [comment]
Yeah, silly me, thanks for quick help :)
