### ISSUE TITLE
Does it work with perspectiveCamera and world space canvas?

### ISSUE THREAD

**Issue by yosun** [cemuka/UnityRuntimeNodeEditor#19]
?

**Comment by cemuka** [comment]
If you plan to scale the canvas like 0.001 then no it won't play well. It shouldn't be problem as long as you keep it around scale 1

**Comment by yosun** [comment]
is there a reason why it is designed to be dependent on canvas scale?

**Comment by cemuka** [comment]
Reason is the unity EventSystem and how it handles pointer events, pixel per unit etc. I'm not sure and haven't tested but you may tweak the canvas settings in your case and see if it works for you.
