### ISSUE TITLE
Line renderer not appearing

### ISSUE THREAD

**Issue by Manurocker95** [cemuka/UnityRuntimeNodeEditor#5]
Line renderer doesn't appear when dragging from node outputs/inputs

**Comment by cemuka** [comment]
Hi @Manurocker95 , currently, input sockets only accepts output, so you could only draw a connection from  output -> input. Well, its sorta feature for now :)

**Comment by Manurocker95** [comment]
> Hi @Manurocker95 , currently, input sockets only accepts output, so you could only draw a connection from output -> input. Well, its sorta feature for now :)

No, I mean, the line renderer is never drawn when dragging from any socket.

Note, this happens in 2021.1.x, 2020.1.x and 2020.3.x, but not in 2019.4.x

**Comment by dayfox5317** [comment]
> > Hi @Manurocker95 , currently, input sockets only accepts output, so you could only draw a connection from output -> input. Well, its sorta feature for now :)
> 
> No, I mean, the line renderer is never drawn when dragging from any socket.
> 
> Note, this happens in 2021.1.x, 2020.1.x and 2020.3.x, but not in 2019.4.x

you need to add  a RequireComponent with CanvasRenderer in UIPrimitiveBase  ( https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/pull-requests/91/fix-to-add-a-requirecomponent-to )
